name: 'Build and publish docker images (all platforms)'

on:
  workflow_dispatch:
  push:
    branches:  # see https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
      - '**'             # matches every branch
      #- master          # matches 'master' branch
      #- '!evil-branch'  # excludes 'evil-branch'
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3  # see https://github.com/docker/metadata-action
        with:
          images: dersimn/helloarm-github-workflow  # list of Docker images to use as base name for tags
          flavor: |
            # Generate 'latest' tag
            #latest=auto
            # Prefix is applied to all tags
            #prefix=some-prefix-for-all-tags-
          tags: |
            # Branch Push Event
            type=ref,event=branch
            # Tag Push Event
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            # Generate SHA tag e.g.: sha-ad132f5
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386, linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
