name: Nightly update check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  check-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: library/alpine:latest
          image: dersimn/helloarm-github-workflow
      - if: ${{ steps.check.outputs.needs-updating }}
        name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: docker.yml
          ref: v2.5.2
