name: Nightly update check

on:
  workflow_dispatch:
  schedule:
    - cron: "14 15 * * *"

jobs:
  check-job:
    runs-on: ubuntu-latest
    outputs:
      needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: library/alpine:latest
          image: library/ubuntu:latest

  trigger-build:
    needs: check-job
    if: ${{ needs.check-job.outputs.needs-updating == 'true' }}
    uses: ./.github/workflows/docker.yml
    secrets: inherit
