name: 'Build and publish docker images (all platforms)'

on:
  workflow_dispatch:
  workflow_call:
  push:
    # branches:
    #   - '**'  # every branch
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: dersimn/helloarm-github-workflow
          tags: |
            # Git Branch
            #type=ref,event=branch
            # Git short SHA: sha-ad132f5
            #type=sha
            # Semantic Versioning
            # 1.1.2
            type=semver,pattern={{version}}
            # 1.1
            type=semver,pattern={{major}}.{{minor}}
            # 1 (disabled if major is zero)
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: dersimn
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: ./Dockerfile
          platforms:
            linux/386,
            linux/amd64,
            linux/arm/v6,
            linux/arm/v7,
            linux/arm64/v8,
            linux/ppc64le,
            linux/s390x
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
